### ISSUE TITLE
Yui (fixed)

### ISSUE THREAD

**Issue by MysticSaba-max** [TMCooper/Anime-Sama-Downloader#1]
Available languages: EN, FR
What is your language? : FR
Pour quiter le programme tapper Q
Quel est le lien de l'animer que vous souhaiter telechargee ? : https://anime-sama.fr/catalogue/tensei-shitara-slime-datta-ken/saison3/vf/
Traceback (most recent call last):
  File "c:\Users\Downloads\Anime-Sama-Downloader-main\Anime_Sama_Downloader.py", line 68, in <module>
    main()
  File "c:\Users\Downloads\Anime-Sama-Downloader-main\Anime_Sama_Downloader.py", line 41, in main
    url_ru = Yui.construct(url_anime_origin, serv_file)
             ^^^
NameError: name 'Yui' is not defined

**Comment by MysticSaba-max** [comment]
import requests
import json
from function import Yui, Cardinal

**Comment by TMCooper** [comment]
normally there is no need to do this the from function.__init__ import * have to take care of the imported

small edit when I tested in the same condition as you the error for my by was not made you may have retouched a line at the start of the program or deleted a file in the function folder

**Comment by MysticSaba-max** [comment]
ok

**Comment by MysticSaba-max** [comment]
I was searching for a anime sama downloader , you are my lfie saver
