### ISSUE TITLE
is it possible to do a search? like you write the name of the anime and it downloads it. not a link

### ISSUE THREAD

**Issue by MysticSaba-max** [TMCooper/Anime-Sama-Downloader#2]
I would really apreciate if you could do this

**Comment by MysticSaba-max** [comment]
so ?

**Comment by TMCooper** [comment]
in fact after having looked at the operation it would be possible yes but it would be necessary to use selenium and using selenium would cause a significant loss of the current speed of the program so I do not think of doing it or in any case perhaps but in a sub-branch of the program

**Comment by MysticSaba-max** [comment]
oh ok no problem

**Comment by Sky-NiniKo** [comment]
Hello, I don't want to make my pub but I just stumble upon your project because of @MysticSaba-max.
Just want to inform you (@TMCooper) that I work on a similar project. If you want to collaborate or just discuss, I am open.

**Comment by TMCooper** [comment]
> Hello, I don't want to make my pub but I just stumble upon your project because of @MysticSaba-max.
> Just want to inform you (@TMCooper) that I work on a similar project. If you want to collaborate or just discuss, I am open.
> I plan to delete this after two week.

hello yeah why not after all i can help you as best as I can, it doesn't pose a problem for me although I work in my free time on my personal projects, nevertheless I can always answer your questions and help you with others.

**Comment by Sky-NiniKo** [comment]
> hello yeah why not after all i can help you as best as I can, it doesn't pose a problem for me although I work in my free time on my personal projects, nevertheless I can always answer your questions and help you with others.

I have some questions about the way you organize/name things link in the function folder.
I think it is preferable to go to DM.
Btw, I also do that on my free time; no pressure to respond fast.

**Comment by TMCooper** [comment]
> [@niniko_](https://discord.com/invite/VKSMKT98)



> > hello yeah why not after all i can help you as best as I can, it doesn't pose a problem for me although I work in my free time on my personal projects, nevertheless I can always answer your questions and help you with others.
> 
> I have some questions about the way you organize/name things link in the function folder. I think it is preferable to go to DM. You can add me on Discord [@niniko_](https://discord.com/invite/VKSMKT98) or send me an email ([pcninik@gmail.com](mailto:pcninik@gmail.com)). Btw, I also do that on my free time; no pressure to respond fast.

yes don't worries I added you on discord don't hesitate to ask me questions once you add me
